# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Weston Thayer
tagline:          blog
url:              http://westonthayer.com/blog/_site/
paginate:         5
baseurl:          /blog/_site/
linkbaseurl:	  /blog/_site
homebaseurl:	  /
assetsurl:		  /blog/_site/public/assets/
author:
  name:           Weston THayer
  url:            https://westonthayer.com
  email:          me@westonthayer.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/Cryclops/portfolio
